services:
    mssql:
        image: mcr.microsoft.com/azure-sql-edge:latest
        ports:
            - 1433:1433
        environment:
            ACCEPT_EULA: 'Y'
            MSSQL_SA_PASSWORD: 'Password123'
            MSSQL_PID: 'Developer'
            MSSQL_USER: 'sa'
